title: AgileSites
subtitle: "AgileSites the easy framework for agile development with WebCenter Sites"
description: "AgileSites the easy framework for agile development with WebCenter Sites"
author: Michele Sciabarra
language: en
timezone: UTC
url: https://hexo.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:snehasen/agilesitesng-website.git

disqus_shortname: hexojs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
swiftype_key: EwN4HMy_KMxTK_GMjV1z
twitter: hexojs
github: hexojs/hexo